### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by aadilayub** [rafaelmardojai/firefox-gnome-theme#1]
Do we clone the repo into the `chrome` folder, or do we just replace our `userChrome.css` with the one in this repo?

 It looks like the `userChrome.css` is dependent on the `themes` folder in this repo, but you cannot tell this from the README.

**Comment by rafaelmardojai** [comment]
README needs some work, also needs a section to show how to enable optional features.

`theme` folder is the theme itself. `userChrome.css` only import it.

You should copy `theme` folder and `userChrome.css` file to your `chrome` Firefox folder.

What do you suggest to make instructions more clear? Change steps 3 & 4 with `git clone https://github.com/rafaelmardojai/firefox-gnome-theme.git chrome`?

Or suggest users to just copy `theme` folder, create `userChrome.css` if no exist and then import what they want?

**Comment by rafaelmardojai** [comment]
I'm also considering create some installation script.

**Comment by alerque** [comment]
For me the ideas solution would be a distro package that fixes up the Firefox on my system rather than mucking around with my profiles on every machine. I would even be willing to help with the packaging for Arch Linux if we can figure out what needs to be put where. Does anybody know what direction to point me in for that?

**Comment by rafaelmardojai** [comment]
Hey @alerque, see #30.
