### ISSUE TITLE
Tor Browser

### ISSUE THREAD

**Issue by icfmp** [rafaelmardojai/firefox-gnome-theme#170]
Hi,

I tried to use firefox gnome theme with Tor Browser but I can't find the user.js file ...

The folder tree is quite different too.

![image](https://user-images.githubusercontent.com/71736258/98089851-97b98900-1e83-11eb-8fb9-fa0c8e4d4bb0.png)

Do you think it is doable ?

Thanks :)

**Comment by rafaelmardojai** [comment]
That looks more like an installation folder.
Have you tried to find your profile folder from `about:support`?

**Comment by rafaelmardojai** [comment]
Any update?

**Comment by KushagraKarira** [comment]
Any update on installing it in tor ?
 ` /opt/tor/Browser/TorBrowser/Data/Browser/profile.default`
Seems to be the profiles folder

**Comment by untermensch** [comment]
To apply this theme to Tor, copy the "chrome" folder from /home/.mozilla/firefox/895b1n39.default-release into /home/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/profile.default

**Comment by Fenimoure** [comment]
> Any update on installing it in tor ? ` /opt/tor/Browser/TorBrowser/Data/Browser/profile.default` Seems to be the profiles folder

Yes, you can install it pretty easily.

# Other thoughts, that might simplify your life

There are some steps from the breakdown below (21­ – 28) that might be eliminated if you rename the directory `~/firefox-gnome-theme-$VERSION` to `~/firefox-gnome-theme`. This is because the install script seems to take the name of the directory it's been run in to name the directory of the theme when installing it into the browser which obviously breaks the script with folders that are named in any other way except `firefox-gnome-theme`.

# Here's a breakdown for Tor 14.0.7 (based on Mozilla Firefox 128.8.0esr):

1. Open Tor
2. Open the ≡ hamburger menu
3. Click Help
4. Click About Firefox
5. Check for the firefox version your Tor Browser is based on
6. Download the corresponding tarball from the [releases](https://github.com/rafaelmardojai/firefox-gnome-theme/releases) page
7. Extract the tarball into your home directory
8. Open `~/firefox-gnome-theme-$VERSION/scripts/auto-install.sh`
9. Remove everything between the parenthesis in `firefoxInstallationPaths=(…)`
10. Go back to Tor Browser
11. Open `about:profiles`
12. Locate `Profile: default`
13. Locate its `Root Directory`
14. Select the path up to `/Browser` (including `/Browser`)
15. Copy the selected text
16. Go back to the file opened at step `8`
17. Between the parenthesis in `firefoxInstallationPaths=()` paste the copied string (example below)
18. Save the file
19. Open a terminal emulator in `~/firefox-gnome-theme-$VERSION` folder
20. Run `./scripts/auto-install.sh` (use chmod +x to make it executable if necessary)
21. Open Tor
22. Go to about:profiles
23. Locate `Profile: default`
24. Locate its `Root Directory`
25. Click `Open Directory`
26. Locate `chrome` folder and open it
27. Rename `chrome/firefox-gnome-theme-$VERSION` to `chrome/firefox-gnome-theme`
28. Repeat steps 19 and 20
29. Restart Tor Browser

# Example for auto-install.sh

```
firefoxInstallationPaths=(
    # Tor
    ~/.var/app/org.torproject.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser # Flatpak
)
```
