### ISSUE TITLE
Some icons and parts are broken since firefox 89

### ISSUE THREAD

**Issue by SeaDve** [rafaelmardojai/firefox-gnome-theme#243]
on new bookmark popover in headerbar:

![image](https://user-images.githubusercontent.com/64297935/120740202-56767e00-c525-11eb-8833-bddd410a0d8d.png)

on headerbar:

![image](https://user-images.githubusercontent.com/64297935/120740222-61c9a980-c525-11eb-9ca9-02a13a080d66.png)
![image](https://user-images.githubusercontent.com/64297935/120740256-76a63d00-c525-11eb-848d-d0e188122c2f.png)
![image](https://user-images.githubusercontent.com/64297935/120740160-3f379080-c525-11eb-80be-e02e2ad9f47f.png)

on hamburger menu:

![image](https://user-images.githubusercontent.com/64297935/120740233-68582100-c525-11eb-9860-c54f63871d52.png)

I'm not sure if this is supposed to happen

![image](https://user-images.githubusercontent.com/64297935/120741013-e0731680-c526-11eb-8e49-7e3b70d80eba.png)

**Comment by rafaelmardojai** [comment]
> on new bookmark popover in headerbar:
> 
> ![image](https://user-images.githubusercontent.com/64297935/120740202-56767e00-c525-11eb-8833-bddd410a0d8d.png)
> 

Fixed.

The menulist (dropdown) is hard to fix completely because how is styled in the firefox side, but I'm looking for a workaround.

The checkboxes theming are on my todo list.

----

> on headerbar:
> 
> ![image](https://user-images.githubusercontent.com/64297935/120740222-61c9a980-c525-11eb-9ca9-02a13a080d66.png)
> ![image](https://user-images.githubusercontent.com/64297935/120740256-76a63d00-c525-11eb-848d-d0e188122c2f.png)
> ![image](https://user-images.githubusercontent.com/64297935/120740160-3f379080-c525-11eb-80be-e02e2ad9f47f.png)

Those were always unthemed because are animated, but now are noticeable with the new firefox icons style. So I decided to theme them. Also fixed the Firefox pages indicator.

----

> on hamburger menu:
> 
> ![image](https://user-images.githubusercontent.com/64297935/120740233-68582100-c525-11eb-9860-c54f63871d52.png)
> 

I can't reproduce the blurred icons.

----

> I'm not sure if this is supposed to happen
> 
> ![image](https://user-images.githubusercontent.com/64297935/120741013-e0731680-c526-11eb-8e49-7e3b70d80eba.png)

Yeah is intended, firefox now only shows the sound button on hover, and that label is the only indicator. I will check if I can find a better way to workaround this.

**Comment by SeaDve** [comment]
thanks! I appreciate your work with the theme
