### ISSUE TITLE
Missed icons in buttons of search pannel

### ISSUE THREAD

**Issue by ai** [rafaelmardojai/firefox-gnome-theme#250]
![20210607172727](https://user-images.githubusercontent.com/19343/121089806-ad928200-c7b5-11eb-8400-fddb18080f0f.png)

Firefox 88, Fedora 34.

Firstly found after new tab design merge (new tabs looks amazing 😍).

**Comment by rafaelmardojai** [comment]
I see checkboxes (that I need to theme) in Firefox 89, but I would say that you shouldn't be using current `master` with Firefox 88 since it targets 89. 

![Captura de pantalla de 2021-06-07 16-35-14](https://user-images.githubusercontent.com/6210397/121090557-63f26900-c7ae-11eb-8d9d-99b6af225fb2.png)

But probably the bug is also present in the `v88` tag, I need to checkout.

**Comment by ai** [comment]
Thanks. We can close this issue. I will have 89 version soon.
