### ISSUE TITLE
Current selected tab in adwaita dark is hard to find

### ISSUE THREAD

**Issue by razzeee** [rafaelmardojai/firefox-gnome-theme#270]
I struggle to quickly find the currently open tab, I think it needs to be more obvious :)

![image](https://user-images.githubusercontent.com/5943908/131047716-643f28c5-15be-45b0-a8b7-783a461123d4.png)

**Comment by rafaelmardojai** [comment]
Are you sure you are using the latest version? There was a issue with using a wrong color, but was fixed since [074304622db66142075be2c27d33ba15df5207ec].

**Comment by razzeee** [comment]
Yes, I think I am, both the manjaro version  https://gitlab.manjaro.org/Chrysostomus/firefox-gnome-theme-maia/-/blob/master/chrome/theme/colors/dark.css and the files on my pc locally do have that change.

**Comment by razzeee** [comment]
Seems like the `dark-maia.css` needs a similar change. If I change that locally it looks better, not sure if it's enough, to quickly find it. Will need some testing :)

**Comment by rafaelmardojai** [comment]
Hey @Chrysostomus, we need to update the maia theme to the latest theme changes, especially in the tabs part, were we removed some vars with the redesign. 

Also I think the maia theme should only overwrite the vars that differ from Adwaita. No need to repeat the same colors since Adwaita colors are always loaded.
