### ISSUE TITLE
[FR] Tab groups like chrome?

### ISSUE THREAD

**Issue by reesericci** [rafaelmardojai/firefox-gnome-theme#345]
Any chance you could implement tab groups like what chrome has?

**Comment by dusansimic** [comment]
I think this is not an issue for this repo. It's something that Firefox could implement, firefox-gnome-theme is just a theme.

**Comment by reesericci** [comment]
well FF is not gonna do it, so I thought I would ask here.

**Comment by rafaelmardojai** [comment]
This theme just modifies the browser CSS, so we're limited to what CSS can do, and this is definitely something that it can't.

I would recommend you any of the existing tab groups add-ons for Firefox, although they have different behavior than Chrome, probably because the Chrome approach is very similar to the build-in Firefox container tabs.
