### ISSUE TITLE
Support diferent GTK themes

### ISSUE THREAD

**Issue by Fatih20** [rafaelmardojai/firefox-gnome-theme#35]
I use the Mojave-Light theme from gnome look and it doesn't use that theme. Any possibility for this to simply adopt the theme from the user instead of having Adwaita coded into it?

**Comment by lionirdeadman** [comment]
No, it's not possible to simply adopt the theme.

Simply put : 
- GTK Stylesheets are not used in Firefox

While we could try to match the color scheme, this theme is heavily **inspired** by Adwaita but it is *not* Adwaita. And that's simply because well, Firefox doesn't use GTK Stylesheets, they use UserChrome Stylesheets which are not the same at all because the items in that stylesheet are not GTK objects.

Someone could fork the project and hardcode it to replicate Mojave-Light but otherwise it's just not feasible.

**Comment by rafaelmardojai** [comment]
I could be partially done using `-moz-appearance`.

For example those properties will call styles adapted to GTK theme, but in a poorly way.
```css
-moz-appearance: button;
-moz-appearance: -moz-window-button-close;
-moz-appearance: -moz-window-titlebar;
```
So will result with the theme looking broken and no polished.

**Comment by rafaelmardojai** [comment]
The only way something like that can be done, as @lionirdeadman mentioned, is separating position/reset styles from color/padding/margin ones. So specific CSS can done for every GTK theme, sharing a base CSS.

But that will make harder maintenance. Port to Saas/Less should be considered, and so on. 
So it's going to be a wontfix, but i can consider doing this work in a future.

**Comment by PitcherTear22** [comment]
> GTK Stylesheets are not used in Firefox

When the default theme is selected in customise, it uses the current GTK theme's colours and close/maximise/minimise icons. Is that not what you are talking about?

**Comment by gitSaptarshi** [comment]
@Fatih20 If you use the Mojave GTK theme from ![vinceliuice](https://github.com/vinceliuice) then you can install the associated ![firefox theme](https://github.com/vinceliuice/Mojave-gtk-theme/tree/master/src/other/firefox). I am using it and it looks like the following (btw I'm using Mojave-dark theme and set firefox theme to dark):
![Screenshot from 2021-01-01 20-07-37](https://user-images.githubusercontent.com/37685073/103440629-32a8c680-4c6d-11eb-90bb-21429f55ed98.png)
