### ISSUE TITLE
(libadwaita branch) light mode tabs bar colouring

### ISSUE THREAD

**Issue by winkelnp** [rafaelmardojai/firefox-gnome-theme#368]
In light mode the tab bar shows colouring that seems to be the inverse of how it is meant to be. the non-focussed tabs look as if they are focussed and vice versa.
This was fine in a previous commit, but now is inverted.
Dark mode is unaffected, and the about:config option "activeTabContrast" resolves it (with the intended "activeTabContrast" effect of course)

Image: 
![Untitled](https://user-images.githubusercontent.com/68015877/166167761-c49f4126-7ae8-491b-8e23-8c63542edc2e.png)

**Comment by CleoMenezesJr** [comment]
The coloring is based on the new tabs which are wip at the moment, in addition I personally prefer it that way since having several tabs it was difficult to know which tab was active, but outside what I like or think, I'm just following what the theme proposes to be: a Libadwaita theme for Firefox
![image](https://user-images.githubusercontent.com/54215258/166288976-27c5b46e-02cf-4c76-b710-5d354d6c5e9a.png)
![image](https://user-images.githubusercontent.com/54215258/166288999-e8b6ede7-f8f3-4705-80c1-01c14363d283.png)

**Comment by bellegarde-c** [comment]
Or maybe make tabs looking like buttons (like in libadwaita).
