### ISSUE TITLE
Close tab system icons

### ISSUE THREAD

**Issue by TomBursch** [rafaelmardojai/firefox-gnome-theme#390]
Is there a reason we explicitly disabled the system close icon for tabs [here](https://github.com/rafaelmardojai/firefox-gnome-theme/blob/f6be71eb185ede978b8e8a0af3be6bde1e3b83a1/theme/system-icons.css#L43)? It seems to me that they are working fine.

**Comment by rafaelmardojai** [comment]
Because in `.tab-close-button` the button style and the icon are the same element, so the CSS filter will affect both.

In the old times when we didn't use SVG icons we had an special styling for the close button using inverted colors, so when the filter was applied it looked ok. Then `system-icons.css` was moved to an optional feature, and probably this was a left over.

So feel free to test and add specific fixes if something looks wrong. I will accept a PR. I don't use `system-icons.css ` and have limited time for this, so is a bit abandoned right now.
