### ISSUE TITLE
Adaptive Tab Coloring

### ISSUE THREAD

**Issue by polyjitter** [rafaelmardojai/firefox-gnome-theme#412]
With libadwaita now including recoloring of windows, and with Safari now dynamically changing the window color based on the currently open webpage, it would be amazing to have the interface of firefox-gnome-theme do something similar.

This would be a large undertaking, and I see it as needing the following:

- A lightweight extension that grabs the current color and assigns it to a CSS variable.
- A refactoring of the way colors are defined in the theme to be generated based on the CSS variable.
- A fallback variable for when this is not enabled or not supported.
- A new preference for enabling or disabling this feature.

For the first bullet point, I believe https://github.com/YS-Wong/Adaptive-Tab-Bar-Color provides adequate logic to cover all use cases needed.

I am willing to work on this, but I would need help. I am new to Firefox extensions and CSS, and would need help setting things up from someone more knowledgeable. If anyone would like to help with this, let's find a place to discuss this more in-depth.

**Comment by rafaelmardojai** [comment]
> A refactoring of the way colors are defined in the theme to be generated based on the CSS variable.

This seems the harder part to me, unless you use JS. So maybe you could generate all the needed CSS variables in the extension. The theme is already using black/light with opacity when posible like libadwaita, so you will only need to override some background colors.

To be honest right now I'm not interested on working in something like this. I only have time to maintain the basic usability of the theme. But if this is implemented behind a pref, I would be happy to review and merge.

**Comment by eilx** [comment]
For anyone interested in [Adaptive Tab Bar Color](https://github.com/YS-Wong/Adaptive-Tab-Bar-Color) support, I've created a gist with the css rules relevant to this that I've been using in my customChrome.css and they seem to work pretty well.

They mostly overwrite the relevant theme variables but I've also added a measure to help with #464 as sadly that issue is especially bad with colored backgrounds, which is visible in the screenshot's url bar.
I've also chosen `--gnome-toolbar-border-color: transparent` by default as having those visible looks bad on colored sites imo (e.g. npmjs.com), but I've left an alternative commented if preferred.

Hopefully this is useful :)
https://gist.github.com/eilx/2e1346472598ddac5e2ec20f40695dfe
#### Google
![image](https://user-images.githubusercontent.com/74159071/198853843-8bc816cc-493d-48e8-8323-9b4aad93e3e2.png)
#### Google + Dark reader
![image](https://user-images.githubusercontent.com/74159071/198853861-ec255ae4-f875-44a8-97d7-7d00ae371f8b.png)
#### The Guardian
![image](https://user-images.githubusercontent.com/74159071/198853893-81b5df11-1138-48f3-8a4a-c25488e2c0e7.png)
#### Npmjs
![image](https://user-images.githubusercontent.com/74159071/198853944-7798b9b1-cac8-474e-9cf1-065aed60a106.png)

**Comment by polyjitter** [comment]
Forgot to comment. This is brilliant work. Thank you so much!

**Comment by Scotty-Trees** [comment]
@eilx Oh wow it does really look amazing. Any updates on your work?

**Comment by rafaelmardojai** [comment]
Anyone is free to send support for the Adaptive Tab Bar Colour extension.

I'm closing this since is out of scope for the theme.
