### ISSUE TITLE
Tab too wide (for me) after updating to the latest version

### ISSUE THREAD

**Issue by JaneSmith** [rafaelmardojai/firefox-gnome-theme#453]
I recently updated to the latest version of Firefox-Gnome-Theme, which includes the new Libadwaita tabs. Unfortunately I do not know which version I was using before updating.

After updating, I immediately noticed that the tabs are quite wide for me. I'm sure this is by design, but as I frequently have over a hundred tabs open, this is very impractical as I can only see around eight tabs at a time.

I searched and found the `gnomeTheme.normalWidthTabs` option, but after enabling that and restarting Firefox, it doesn't seem to have made any difference whatsoever. Perhaps this option is bugged?

What can I do to make the tabs smaller? Thanks.

**Comment by rafaelmardojai** [comment]
Yeah, I have increased the min-width of the tabs to `150px` (although Adwaita tabs are `126px`, so possibly I will move to that size for consistency) because IMO when I have too many tabs open I can barely read the label with the `76px` that Firefox has by default.

`gnomeTheme.normalWidthTabs` only reverts the tabs taking all te available space when they are few, but I could make it also bring back the `76px` min-width.

**Comment by JaneSmith** [comment]
Thanks for clarifying that. If possible then, I'd appreciate it if `gnomeTheme.normalWidthTabs` could bring back the 76px min-width, or perhaps a separate setting for that if that works better for more flexibility. Of course the goal is to match Adwaita, but for me personally I really need the tabs to be more compact so I can navigate them more easily. Thanks.

**Comment by carlocastoldi** [comment]
> or perhaps a separate setting for that if that works better for more flexibility.

I know it's a bit too much to ask, but would it be possible to make it a separate setting? I like having wide tabs when possible. But when windows are full of tabs i'd rather see them all than scroll over the tabs to see which ones are open
