### ISSUE TITLE
Unable to set the color used in the theme

### ISSUE THREAD

**Issue by Nakamerica** [rafaelmardojai/firefox-gnome-theme#535]
Hi, I've used ./scripts/install.sh and the flag to get the yaru theme, but I cannot seem to get the theme applied... I believe it's the adwaita theme that gets applied regardless:

![Screenshot from 2022-12-25 06-04-07](https://user-images.githubusercontent.com/88226614/209454140-204ddae2-5ed8-4542-8744-1009c797c907.png)
![Screenshot from 2022-12-25 06-16-54](https://user-images.githubusercontent.com/88226614/209454173-6c7b069a-a790-41e8-b649-3c8a953fd816.png)

Thank you for any clarification on this.

**Comment by rafaelmardojai** [comment]
The Yaru variant right now only changes our internal `--gnome-accent`  CSS var (that's why you see the fast.com label in orange). This variant was contributed by the community a long time ago and became unmaintained, so I probably should just remove it for now.

The urlbar suggestions active item uses the `--gnome-accent-bg` CSS bar for example.
