### ISSUE TITLE
Make private windows white

### ISSUE THREAD

**Issue by julianfairfax** [rafaelmardojai/firefox-gnome-theme#541]
**Is your feature request related to a problem? Please describe.**
Private windows are blue, whereas in GNOME Web they're white

**Describe the solution you'd like**
Make them white

**Comment by rafaelmardojai** [comment]
GNOME Web private window headerbar is blue, but light blue of course.

We already theme it like that, but the problem is more complex, Firefox has started to force the dark color scheme CSS media query on the private window UI (since Firefox 107 probably).

So I don't know if I can detect light theme in private window anymore, at least no without breaking it for dark theme users.

**Comment by rafaelmardojai** [comment]
> In any case, the buttons on the private window (with browser.theme.dark-private-windows set to false) are the wrong colour, unless they're being hovered over, in which case they are the right colour.

You mean the window controls right? Yeah just noticed it.

I also will be setting `browser.theme.dark-private-windows` to `false` in our `user.js` config.
