### ISSUE TITLE
[Vertical tab - Extension] Weird artifact after updating to v117

### ISSUE THREAD

**Issue by astrocaat** [rafaelmardojai/firefox-gnome-theme#664]
As it can be seen from the screenshot, there's a top blank gap and it's also not placed correctly under the bookmarks tab. The bookmark tab is visible only on the homepage and when it's hidden the extension behaves correctly.   

**Screenshots**
![Screenshot from 2023-09-03 15-29-32](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/143425234/7062b1ec-b35a-4ff1-9e63-de4cfd8d569b)

**Setup information**
 - OS: ArchLinux
 - Installation method: AUR - git package
 - Firefox version: 117
 - Theme version: latest commit

**Comment by rafaelmardojai** [comment]
CC @BirdInFire

**Comment by BirdInFire** [comment]
will check that during the week

**Comment by astrocaat** [comment]
@BirdInFire by any chance do you have any updates?

**Comment by BirdInFire** [comment]
@astrocaat I remember now that while I worked on this I have seen this bug.

The actual problem is the fact that I cannot fix it without breaking "normal" page, since the extension do detect the size of the "browser" on normal page, I have an easy fix in mind but it do require JS to do, and theming of firefox don't allow js at all

I'm searching alternative way to push it behind the menu tab without actually pushing it behind the actual website, I cannot promise I will find a fix but I will try.

**Comment by BirdInFire** [comment]
have fixed it do the PR right now

**Comment by BirdInFire** [comment]
the fix also apply the "animation" from the vertical tab to the "bookmarks" tab to make it more natural (like it retract itself when leaving the newtab page)
