### ISSUE TITLE
[Feature] Color themes

### ISSUE THREAD

**Issue by AxelSkye** [rafaelmardojai/firefox-gnome-theme#690]
**Is your feature request related to a problem? Please describe.**
If you use multiple profiles or just want some customization a common way is to choose a color theme. Standard Firefox themes change tabs' outline, but it would be cool if they applied the color while keeping all the theme customization. Even though libadwaita doesn't include this, it would be a good balance between looking stock and being customizable.

**Describe the solution you'd like**
Offer color "accents" or apply Firefox's themes color.

New Google Chrome refreshed desgin handles this quite good, using custom colors with both light and dark theme support, the same + this customization for Firefox would be amazing.

**Comment by rafaelmardojai** [comment]
You could use something like Gradience that also supports tweaking this theme, but you will get the customization in all GTK apps. An advanced alternative would be to use the Gradience output or manually editing the colors CSS files of the theme (`firefox-gnome-theme/theme/colors`) where you can edit each CSS variable.

About supporting Firefox color themes, I haven't investigated if it is feasible to support it but I also lack the motivation.

**Comment by Zetta1Reid0** [comment]
Okkkk . So why doesn't the theme actually use Firefox predefined variables for colors ? See : https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions#values. That way this theme can pick up color from your gtk theme directly. And since most people actually either patch libadwaita to support theming ,use global variable GTK_THEME to force the theme or use the "@include" rule to override whole theme from user "&XDG_CONFIG_DIR/gtk-4.0/gtk.css" config file , because Adwaita theme is ugly for some (if not most) people and doesn't match their gtk theme. There could also be a switch to use libadwaita defines colors . See : https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/named-colors.html . As for motivation this should be enough.

**Comment by NoTuxNoBux** [comment]
It might not be what this ticket was initially about, but GNOME 47 offers accent colours now:

![afbeelding](https://github.com/user-attachments/assets/f7c570c5-6149-4c2c-8fed-3c147e80d4af)

These are a couple of stock colours that are then used instead of the traditional 'GNOME blue'. If you use them, however, it will then go out of sync with the Firefox theme because it uses only the blue. Perhaps there can just be a sort of include file for every accent colour in GNOME with the necessary colour variables set for this, though?
