### ISSUE TITLE
Not sure if a bug or not - tab close button is now on left side

### ISSUE THREAD

**Issue by mikoducky** [rafaelmardojai/firefox-gnome-theme#702]
**Describe the bug**
The tab close button is now on the left side of tabs instead of the right.

**To Reproduce**
1. Install theme with curl script or autoinstall
2. That's it.

**Expected behavior**
The close button for tabs should be on the right side of the tab.

**Setup information**
 - OS: Manjaro
 - Installation method: Pre-installed
 - Firefox version: 120
 - Theme version: Default
 - Optional features enabled: None

**Comment by mikoducky** [comment]
I just found out that the close on the tab is linked to what side your window close button is. I don't remember it being that way just a couple days ago... Could we maybe have a feature to enable changing the side you want that on without affecting the window buttons placement?

**Comment by rafaelmardojai** [comment]
Yep, the behavior changed some months ago (this commit 8c9db7a9cdd2012868e0fc97b329d1f2a7af9823), it has been a long standing request. 

I implemented it like that because GNOME Web behaves like that, although other GNOME apps with tabs like Files or Console don't seem to be consistent with that behavior.  Another reason is that "left close button" users seemed to agree about having the tabs button in the left too, but looks like I was wrong 😅.

**Comment by mikoducky** [comment]
I'm great at being contradictory. I just think it looks weird, especially when being on the first tab, as the close buttons end up being awkwardly stacked. How much of a pain would it be to have it as a optional feature to enable in the about:config? Like, the value would literally just flip the side it's currently on, not even specify which one.

**Comment by rafaelmardojai** [comment]
Added the `gnomeTheme.swapTabClose` pref, it will swap the position of the tab close button that by default follows the window controls position.

**Comment by mikoducky** [comment]
> Added the `gnomeTheme.swapTabClose` pref, it will swap the position of the tab close button that by default follows the window controls position.

Works great. Thanks so much!
