### ISSUE TITLE
[Vertical tab - Extension] Tab bar overlaps the bookmarks bar when bookmarks set to "Only Show on New Tab"

### ISSUE THREAD

**Issue by LinuxSBC** [rafaelmardojai/firefox-gnome-theme#714]
**Describe the bug**

When the bookmarks bar is set to "Only Show on New Tab" and a new tab is open, the vertical tab bar overlaps the left side of the bookmarks bar, hiding the leftmost bookmark(s). This does not occur when the bookmarks bar is always or never shown.

**To Reproduce**

1. Right click on the bookmarks bar or title bar.
2. Under "Bookmarks Toolbar," select "Only Show on New Tab."
3. Open a new tab.
4. Observe the bookmarks bar being partially covered by the tab bar.

**Expected behavior**

The tab bar would move down with the bookmarks bar so that they do not overlap.

**Screenshots**

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/18235310/b8c306ab-32c5-4b2b-94df-8f82c899d99c)

**Setup information**
 - OS: Fedora Silverblue
 - Installation method: Both Flatpak and RPM
 - Firefox version: 120, but it also happened on earlier versions
 - Theme version: v120, but it also happened on earlier versions
 - Optional features enabled: gnomeTheme.extensions.tabCenterReborn

**Comment by BirdInFire** [comment]
Thanks for your report I will also follow it here : https://github.com/rafaelmardojai/firefox-gnome-theme/issues/664

Both show the same error, there is the answer I given (5 minutes ago :) )

@LinuxSBC I remember now that while I worked on this I have seen this bug.

The actual problem is the fact that I cannot fix it without breaking "normal" page, since the extension do detect the size of the "browser" on normal page, I have an easy fix in mind but it do require JS to do, and theming of firefox don't allow js at all

I'm searching alternative way to push it behind the menu tab without actually pushing it behind the actual website, I cannot promise I will find a fix but I will try.

**Comment by BirdInFire** [comment]
I have fixed it do the PR now

**Comment by BirdInFire** [comment]
the fix also apply the "animation" from the vertical tab to the "bookmarks" tab to make it more natural (like it retract itself when leaving the newtab page)
