### ISSUE TITLE
[Feature] Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [rafaelmardojai/firefox-gnome-theme#738]
**Is your feature request related to a problem? Please describe.**
GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Describe the solution you'd like**
It would be nice if the project's code were moved to GitLab or Codeberg.

**Comment by BirdInFire** [comment]
**2 questions :** 

1. What will this change can offer to the project ? (if you don't count political or any idea related choice)
2. Will it cause other unforeseen consequences ?

**I can already predict some consequences like :** 

- Auto update of some script falling.
- More difficulty to be found by "normal" people / dev who don't really care about the platform.
- Reduction of the security of the project (since unless other alt you propose GitHub do impose on code creator to have 2FA (to protect against supply chain attack)).
- Duplicate issue here and on the new one
- Make a lot of dead link of blog etc who advertised this project over the years (if this one is close other wise go read the duplicate issue).
- More difficulty to find dev to help (those service have less users than GitHub and many dev won't create an account for 1 commit / issue).

**My own choice if this issue pass :** 

In my case if this project move I will stop any support for vertical tab immediately since I do not intent to move to a less secure (by default) alternative of GitHub only for political purpose.

**Comment by rafaelmardojai** [comment]
I'm using Codeberg (and my own Forgejo instance) for new projects, but I have no plans to migrate any of my projects for the time being, and less likely big projects like this. Along with other cons mentioned by @BirdInFire, I personally lack the time for such a migration.

Also I must say that I don't think other alternatives are less secure, and with migrations you can always move the issues and archive the old repo to avoid duplication.

I may add a mirror on Codeberg in the near future, so that the code is also available on a more open platform.

**Comment by BirdInFire** [comment]
> I'm using Codeberg (and my own Forgejo instance) for new projects, but I have no plans to migrate any of my projects for the time being, and less likely big projects like this. Along with other cons mentioned by @BirdInFire, I personally lack the time for such a migration.
> 
> 
> 
> Also I must say that I don't think other alternatives are less secure, and with migrations you can always move the issues and archive the old repo to avoid duplication.
> 
> 
> 
> I may add a mirror on Codeberg in the near future, so that the code is also available on a more open platform.

What I mean by less secure is the fact that you cannot be sure that the guy or gal that push the code have a secure account and one day he might be hijacked and push hidden malicious code mandatory 2FA from GitHub reduces very much the risk where other without this rules not
