### ISSUE TITLE
Address bar get covered by suggestions when clicked

### ISSUE THREAD

**Issue by malfisya** [rafaelmardojai/firefox-gnome-theme#788]
**Describe the bug**

Address bar get covered by suggestions when clicked.

**To Reproduce**

1. Click address bar
2. See error

**Expected behavior**

The address bar shouldn't be covered behind suggestion

**Screenshots**

![Screenshot from 2024-05-15 10-07-10](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/101771435/dc344b4d-28cd-4aae-a843-379e6866cdaf)

**Setup information**
 - OS:  Solus 
 - Installation method:  from repository (eopkg)
 - Firefox version:  126
 - Theme version:  125
 - Optional features enabled:  gnomeTheme.systemIcons

**Additional context**

Nothing

**Comment by listout** [comment]
Can confirm this happened.

**Comment by vermario** [comment]
I noticed the same and: 

1. with this code in `customChrome.css` you can affect the positioning of the bar: 

```css
/* URL bar results */
.urlbarView {
	margin: 45px 0 0 -3px !important;
}
```
But it seems to me there's some bigger change at work here, since even if we move the bar results out of the way, the url bar itself is empty (and you cannot for example copy the current url of the page anymore):

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/185412/1783fc71-e22b-4512-a018-de51701c4dde)

**Comment by Vigilaterr** [comment]
On arch had same issue. Just reinstall theme by using git clone and install.sh. It solved the problem for me

**Comment by malfisya** [comment]
It was fixed on master branch after all https://github.com/rafaelmardojai/firefox-gnome-theme/pull/782. So this is a duplicate of https://github.com/rafaelmardojai/firefox-gnome-theme/issues/771. Closing.
