### ISSUE TITLE
Back navigation on navbar and close button merged

### ISSUE THREAD

**Issue by nithamitabh** [rafaelmardojai/firefox-gnome-theme#813]
![image](https://github.com/user-attachments/assets/e1e6a6ab-1898-4622-8bcb-3d12bdb6653c)

There are two issues here first back navigation button merged with close button so i can't able to navigate back by clicking I have to use keyboard shortcut for that second issue i face is that icon not look same as macOS as you see preview image.
I am using this windows it running fine there, but on Ubuntu 24.04 and my Mozilla Firefox version is 126.0.1 .

**Comment by rafaelmardojai** [comment]
Please use the bug template next time.

If I understand well, you're running Firefox 126.0.1 on Ubuntu 24.04 right? What optional preferences are you using? (maybe `gnomeTheme.systemIcons` since those icons are not included on the theme).

But in general you don't seem to be using this theme, maybe some fork? We don't have that macOS style in the theme. Maybe you're using this fork https://github.com/vinceliuice/WhiteSur-firefox-theme? If so, please report the bug there.
