### ISSUE TITLE
[Feature] Dark mode in private windows, or a matching blue color

### ISSUE THREAD

**Issue by yokoffing** [rafaelmardojai/firefox-gnome-theme#818]
**Is your feature request related to a problem? Please describe.**

Even after resetting `browser.theme.dark-private-windows`, the new tab page for Private Windows is white.

**Describe the solution you'd like**

Either:
1) Direct users in the README what line to delete in the userChrome files so that private mode is dark, or provide a custom fix.
2) Make the page color match the navy / dark blue private browser theme you provide, by default.

**Describe alternatives you've considered**

**Additional context**

**Comment by rafaelmardojai** [comment]
I don't think you can reset `browser.theme.dark-private-windows` since it's set in the `user.js` file and will be loaded again every time you restart Firefox.

I can add documentation in the README about removing that pref from `user.js`. But the behavior of respecting the system color scheme in private windows is what GNOME Web does, so we'll keep that pref set to `false` in the theme.

**Comment by yokoffing** [comment]
> I don't think you can reset browser.theme.dark-private-windows since it's set in the user.js file and will be loaded again every time you restart Firefox.

I remove the pref from the user.js and reset in about:config, then restart. But it doesn't look great. Alternatively, I think a blue page theme to match the address bar etc. would look nice. In other words, if we're using a custom theme for the private window, continue it into the page.

I'm not trying to nit-pick. But if we're not using a purple theme or dark theme, then we should extend the blue theme onto the page, instead of the glaring white.

I hope that makes sense. Thanks for the great project!
