### ISSUE TITLE
WINDOWS BUTTOM NOT COLOR

### ISSUE THREAD

**Issue by yayangkasep** [rafaelmardojai/firefox-gnome-theme#822]
![Screenshot from 2024-08-12 23-24-14](https://github.com/user-attachments/assets/e5c3b826-404e-414c-a00f-ad7e1a91ecc4)

i use [https://github.com/vinceliuice/WhiteSur-gtk-theme](https://github.com/vinceliuice/WhiteSur-gtk-theme) why windows button control color not apply?

**Comment by rafaelmardojai** [comment]
Because window buttons are always styled like libadwaita ones.

There's an issue already open to add an optional pref to not theme the window buttons, see #320.

But any way, the GTK theme you're using has a fork of this theme with its styles applied, check https://github.com/vinceliuice/WhiteSur-gtk-theme/tree/master/src/other/firefox.
