### ISSUE TITLE
[Feature] maintain a copr repo.

### ISSUE THREAD

**Issue by CodedIsTaken** [rafaelmardojai/firefox-gnome-theme#860]
to make it more straightforward and accessible to install on fedora I’m asking for you to open a copr repo on fedora copr, this should provide a easy way to install Firefox gnome theme for fedora.

**Comment by rafaelmardojai** [comment]
Sadly I don't have time to maintain that, but the community can take care of that if interested.

**Comment by CodedIsTaken** [comment]
> Sadly I don't have time to maintain that, but the community can take care of that if interested.

I’ll work on finding a maintainer.

**Comment by CodedIsTaken** [comment]
Hey, here's an update

here's a better more easier method.

ask the guys of this repo to maintain a package for your theme https://terra.fyralabs.com/

**Comment by Froggy232** [comment]
Hi,
I just wanted to add that another way is to use "[Add Water](https://github.com/largestgithubuseronearth/addwater)", a flatpak app (that works for every type of firefox install I think) that can install, update, remove and even enable or disable theme options. It has the ability to regularly check for theme update in background, and automatically apply them.
It's a nice option especially if you use an immutable distro like Silverblue or simply firefox with flatpak, as it's a flatpak itself and integrate very well with the environment. It's more flexible than a copr because it doesn't require a maintainer, works for every type of install, and works for every linux distro, not only fedora based like a copr would be.
It's just my two cents, but I think it's a better solution than a specific package and repo, also way more user friendly.
Best regards

**Comment by CodedIsTaken** [comment]
> Hi, I just wanted to add that another way is to use "[Add Water](https://github.com/largestgithubuseronearth/addwater)", a flatpak app (that works for every type of firefox install I think) that can install, update, remove and even enable or disable theme options. It has the ability to regularly check for theme update in background, and automatically apply them. It's a nice option especially if you use an immutable distro like Silverblue or simply firefox with flatpak, as it's a flatpak itself and integrate very well with the environment. It's more flexible than a copr because it doesn't require a maintainer, works for every type of install, and works for every linux distro, not only fedora based like a copr would be. It's just my two cents, but I think it's a better solution than a specific package and repo, also way more user friendly. Best regards

A Terra repo is also great considering you don't need to do any extra work on his part.

**Comment by rafaelmardojai** [comment]
The problem with system packages is that Firefox theme's are installed in user space, so you can't just make packages to install a theme in a profile in the `~/.mozilla` folder. Firefox doesn't have a mechanism for global themes.

That means that a package can install and update the theme in a system location, but the user must symlink that location from their Firefox profile folder. For example this is what you must to do after installing the AUR package: https://aur.archlinux.org/cgit/aur.git/tree/INSTALL.md?h=firefox-gnome-theme

So yeah, IMO **Add Water** is the most friendly option if you want to avoid manual install or bash scripts.
